apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kursach
commonLabels:
  app: mongo
resources:
- mongos.yaml
configMapGenerator:
- name: mongos-entrypoint
  files:
  - cfg_svr_setup.sh
  - mongos_start.sh