apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  #serviceName: "mongos"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongos
        environment: test
    spec:
      serviceAccountName: mongodb
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
          - "/bin/bash"
          - ls
          - /mnt/entrypoint
          volumeMounts:
            - mountPath: /mnt/entrypoint
              name: mongos-entrypoint
          env:
          - name: CFG_SVR_NAME
            value: cfg-svr
          - name: CFG_SVR_SVC
            value: cfg-svr
          - name: CFG_SVR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
            - containerPort: 27017
      volumes:
      - name: mongos-entrypoint
        configMap:
          name: mongos-entrypoint