apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmitter
spec:
  selector:
    matchLabels:
      app: transmitter
  replicas: 1
  template:
    metadata:
      labels:
        app: transmitter
    spec:
      containers:
      - name: transmitter
        image: daniilzhyrov/flask:latest
        command: ["python3"]
        args:
          - "/mnt/entrypoint/app.py"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /mnt/entrypoint
          name: transmitter
      volumes:
      - name: transmitter
        configMap:
          name: transmitter
