apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmitter
spec:
  selector:
    matchLabels:
      app: transmitter
  replicas: 1
  template:
    metadata:
      labels:
        app: transmitter
    spec:
      containers:
      - name: transmitter
        image: daniilzhyrov/kursach-transmitter:latest
        ports:
        - containerPort: 5000

