apiVersion: v1
kind: Service
metadata:
  name: transmitter
  namespace: kursach
  labels:
    app: transmitter
spec:
  selector:
    app: transmitter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
