apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kursach
commonLabels:
  app: ds-generator
resources:
- deploy.yaml
# configMapGenerator:
# - name: ds-generator
#   files:
#     - dataset.csv