apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kursach
commonLabels:
  app: mongo
resources:
- shard-job.yaml
configMapGenerator:
- name: shard-job-entrypoint
  files:
    - entrypoint.sh