apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kursach
commonLabels:
  app: mongo
resources:
- svc-acc.yaml
- roles.yaml
- svcs.yaml
- rs0.yaml
- rs1.yaml
- cfg-svr.yaml
bases:
- mongos
# - shard-job