apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kursach
commonLabels:
  app: mongo
resources:
- crds.yaml
- svc-acc.yaml
- roles.yaml
- crbs.yaml
- operator.yaml
- mongo-cluster.yaml