apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-enterprise-operator
  namespace: kursach
spec:
  replicas: 1
  selector:
      matchLabels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: mongodb-enterprise-operator
        app.kubernetes.io/instance: mongodb-enterprise-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: mongodb-enterprise-operator
        app.kubernetes.io/instance: mongodb-enterprise-operator
    spec:
      serviceAccountName: mongodb-enterprise-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      containers:
      - name: mongodb-enterprise-operator
        image: quay.io/mongodb/mongodb-enterprise-operator:1.10.0
        imagePullPolicy: Always
        args:
          - "-watch-resource=mongodb"
          - "-watch-resource=opsmanagers"
          - "-watch-resource=mongodbusers"
        command:
          - "/usr/local/bin/mongodb-enterprise-operator"
        resources:
          limits:
            cpu: 1100m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 200Mi
        env:
        - name: OPERATOR_ENV
          value: prod
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CURRENT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IMAGE_PULL_POLICY
          value: Always
        # Database
        - name: MONGODB_ENTERPRISE_DATABASE_IMAGE
          value: quay.io/mongodb/mongodb-enterprise-database
        - name: INIT_DATABASE_IMAGE_REPOSITORY
          value: quay.io/mongodb/mongodb-enterprise-init-database
        - name: INIT_DATABASE_VERSION
          value: 1.0.2
        - name: DATABASE_VERSION
          value: 2.0.0
        # Ops Manager
        - name: OPS_MANAGER_IMAGE_REPOSITORY
          value: quay.io/mongodb/mongodb-enterprise-ops-manager
        - name: INIT_OPS_MANAGER_IMAGE_REPOSITORY
          value: quay.io/mongodb/mongodb-enterprise-init-ops-manager
        - name: INIT_OPS_MANAGER_VERSION
          value: 1.0.3
        # AppDB
        - name: APPDB_IMAGE_REPOSITORY
          value: quay.io/mongodb/mongodb-enterprise-appdb
        - name: APPDB_AGENT_VERSION
          value: 10.2.15.5958-1_4.2.11-ent
        - name: INIT_APPDB_IMAGE_REPOSITORY
          value: quay.io/mongodb/mongodb-enterprise-init-appdb
        - name: INIT_APPDB_VERSION
          value: 1.0.6
        - name: OPS_MANAGER_IMAGE_PULL_POLICY
          value: Always