apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rs1
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: rs1
        environment: test
    spec:
      serviceAccountName: mongodb
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs1
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=rs1,environment=test"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: mongo
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi