apiVersion: v1
kind: Service
metadata:
  name: rs0
  labels:
    name: rs0
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: rs0
---
apiVersion: v1
kind: Service
metadata:
  name: rs1
  labels:
    name: rs1
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: rs1