apiVersion: v1
kind: Service
metadata:
  name: rs0
  labels:
    role: rs0
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: rs0
---
apiVersion: v1
kind: Service
metadata:
  name: rs1
  labels:
    role: rs1
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: rs1
---
apiVersion: v1
kind: Service
metadata:
  name: cfg-svr
  labels:
    role: cfg-svr
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: cfg-svr
---
apiVersion: v1
kind: Service
metadata:
  name: mongos
  labels:
    name: mongos
spec:
  selector:
    name: mongos
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: NodePort